/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("fr.cyu.smartread.java-library-conventions")
}
dependencies {
    api(project(":deeplearning"))
}