/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("fr.cyu.smartread.java-application-conventions")
}

dependencies {
    implementation("org.jfree:jfreechart:1.5.4")
    implementation("org.apache.commons:commons-text")
    implementation(project(":deeplearning"))
    implementation(project(":spellchecking"))
}

application {
    // Define the main class for the application.
    mainClass.set("fr.cyu.smartread.app.App")
}
